import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import FontLocal from '@next/font/local'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import Navigation from '../components/Layout/Navigation'
import News from '../components/sections/News'
import Blogs from '../components/sections/Blogs'
import Responsibility from '../components/sections/Responsibility'
import Report from '../components/sections/Report'
import Footer from '../components/Layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>soprasteria</title>
        <meta name="description" content="Generated by sera" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
      <Hero/>
      <News />
      <Blogs/>
      <Responsibility/>
      <Report />
      <Footer/>
    </>
  )
}
